# object for reference only
ref:
  docker_default: &docker_default
    docker:
      - image: python:3.5
    working_directory: /tmp/app
    environment:
      TZ: /usr/share/zoneinfo/Asia/Taipei
      # https://docs.pipenv.org/advanced.html#custom-virtual-environment-location
      WORKON_HOME: /tmp/app/.venv

jobs:
  build:
    <<: *docker_default
    steps:
      - checkout
      - restore_cache:
          keys:
            - purewords-cache-20180807-{{ checksum "Pipfile.lock" }}
            - purewords-cache-20180807
      - run:
          name: Install pipenv
          command: pip install pipenv==v2018.05.18
      - run:
          name: Install dependencies
          command: |
            pipenv run pip install -U Cython
            pipenv install --dev
      - save_cache:
          key:  purewords-cache-20180807-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - persist_to_workspace:
          root: .
          paths:
            - .venv
  flake8:
    <<: *docker_default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Flake8
          command: pipenv run python -m flake8 .
  test:
    <<: *docker_default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Unit Tests
          command: pipenv run python -m unittest

workflows:
  version: 2
  build-and-lint-and-test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - flake8:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - flake8
          filters:
            tags:
              only: /.*/
