# This is a default config for purewords

# tokenizer setting
tokenizer : 'yoctol_jieba'

# removing meaning notation setting
remove_url : True
remove_time : True
remove_phone_number : True
replace_title : True
replace_abbreviation : True
remove_angle_brackets: True

# removing stopwords setting
stopwords_path : 'configs/stopwords.txt'

# splitting sentences setting
max_len : 200
min_len : 1

# multiprocess setting
thread_num : 32
